# Generated by Django 3.2.9 on 2021-11-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='accounts.account')),
                ('linked_accounts', models.ManyToManyField(blank=True, related_name='_accounts_linkedaccounts_linked_accounts_+', to='accounts.Account')),
            ],
        ),
    ]
