# Generated by Django 3.2.9 on 2022-03-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_linkedaccounts'),
    ]

    operations = [
    ]
