# Generated by Django 3.2.9 on 2022-03-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220325_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_apps', to='accounts.account')),
                ('apps', models.ManyToManyField(blank=True, related_name='_accounts_linkedapp_apps_+', to='accounts.RigApp')),
            ],
            options={
                'ordering': ('account__name',),
            },
        ),
    ]
