# Generated by Django 3.2.9 on 2022-03-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_linkedapp_rigapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='last_used_app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_user_app', to='accounts.rigapp'),
        ),
    ]
